### PR TITLE
WIP custom http headers

### PR DESCRIPTION
**Pull request by lachie**
Simple facility for setting custom http headers.
WIP because I'm not quite sure how to test.

Need a repeatable site like `challenge.flood.io` to test this from a smoke test.
I tried setting User-Agent, but you need to do that via `setUserAgent`.

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
We could test with setting content-type on something and making it return JSON?

**Comment by ivanvanderbyl** [comment]
I think we should ship this as is, WDYT @lachie ?

**Comment by mattisa** [comment]
Will this be merged?
Just waiting this change to bypass some stuff on load testing.

**Comment by 90kts** [comment]
@lachie http://flooded.io/headers will echo back any request headers

**Comment by 90kts** [comment]
Note you'll also need to bust past the varnish cache on that endpoint for testing with unique parameter e.g. `curl -H "Special: Sauce" "http://flooded.io/headers?param=$(date +%s%N)"`

**Comment by jiffypopjr** [comment]
Would love to use this, what is holding it up from the merge?!

**Comment by ivanvanderbyl** [comment]
@jiffypopjr @mattisa we'll get this into the next release.

**Pull request merged**
